[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["google-auth-library", "googleapis"]
  node_bundler = "esbuild"